#!/bin/sh

PREREQ="udev network"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

[ -x /sbin/hostapd ] || exit 0


run_hostapd() {
    local flags="/etc/hostapd/hostapd.conf"
    
    log_begin_msg "Setting monitor mode..."	
    ifconfig wlan0 up
    ifconfig wlan0 192.168.2.1 netmask 255.255.255.0 broadcast 192.168.2.255
    route add 192.168.2.0/24 dev wlan0
    iw wlan0 interface add mon0 type monitor 
    ifconfig mon0 up
   
    log_begin_msg "Starting hostapd..."

    exec /sbin/hostapd $flags
}

. /scripts/functions
sleep 10
run_hostapd &
echo $! >/run/hostapd.pid

