#!/bin/sh

PREREQ="udev network"

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
    ;;
esac

[ -x /sbin/iptables ] || exit 0

run_iptables() {

    log_begin_msg "Creating iptables rules for Vpn over TOR..."

    ### ADD IPTABLES RULES ###
    iptables-nft -F
    iptables-nft -X
    iptables-nft -t nat -F
    iptables-nft -t nat -X 
    iptables-nft -t mangle -F
    iptables-nft -t mangle -X
    iptables-nft -P INPUT ACCEPT
    iptables-nft -P FORWARD ACCEPT
    iptables-nft -P OUTPUT ACCEPT

    ### END IPTABLES RULES ###
}

. /scripts/functions

run_iptables &
echo $! >/run/iptables.pid
