#!/bin/sh

PREREQ=""

prereqs() {
	echo "$PREREQ"
}

case "$1" in
	prereqs)
		prereqs
		exit 0
	;;
esac

. /scripts/functions
EXE="$(readlink -f /sbin/openvpn)" && [ -f "$EXE" ] || exit 1

if PID="$(cat /run/openvpn.pid)" 2>/dev/null &&
        [ "$(readlink -f "/proc/$PID/exe")" = "$EXE" ]; then
    log_begin_msg "Stopping OpenVPN..."

    # Kill all process groups the leader of which is a child of the openvpn process
    # (busybox's kill doesn't accept multiple -PGID so we use a while loop)
    sed -nr "s/^([0-9]+) \\(.*\\) \\S $PID \\1 .*/\\1/p" \
        /proc/[0-9]*/stat 2>/dev/null | \
        while read pgid; do kill -TERM -"$pgid"; done

    # Kill remaining children (there shouldn't be any)
    sed -nr "s/^([0-9]+) \\(.*\\) \\S $PID [0-9]+ .*/\\1/p" \
        /proc/[0-9]*/stat 2>/dev/null | \
        while read pid; do kill -TERM "$pid"; done

    kill -TERM "$PID"
    log_end_msg
fi



